# The 49 standard fields from the import template (import1_2.xlsx)
TARGET_FIELDS = [
    "Reference1", "Reference2", "Reference3",
    "Container ID", "Container Type",
    "Pallet ID", "Pallet Type",
    "Collection ID", "Collection Type",
    "Internal Account Number/Subclient",
    "Shipper Name", "Shipper Address 1", "Shipper Address 2", "Shipper Address 3",
    "Shipper City", "Shipper State", "Shipper Zip/Postcode",
    "Shipper Country Code", "Shipper IOSS",
    "Consignee", "Consignee Address1", "Consignee Address2", "Consignee Address3",
    "Consignee City", "Consignee State", "Consignee Zip/Postcode",
    "Consignee Country Code", "Consignee Email", "Consignee Phone", "Consignee EORI",
    "Package type", "Pieces",
    "Item Quantity", "Item Weight", "Item Value",
    "Line Weight", "Line Value", "Total Weight", "Total Value",
    "Weight UOM", "Currency", "Incoterms", "Shipping rate",
    "Description", "TARIC code", "Item SKU",
    "Item Country of origin", "Weblink", "Notes"
]

# Comprehensive header aliases — built from sample files + client's training pack + APC file
# Maps known source headers (lowercased) → canonical target field
HEADER_ALIASES = {
    # ── Reference1 ───────────────────────────────────────────────────
    "reference1": "Reference1",
    "ref1": "Reference1",
    "tracking number": "Reference1",
    "tracking_number": "Reference1",
    "consignment number": "Reference1",
    "sendungsnummer": "Reference1",
    "referentie 1": "Reference1",
    "référence 1": "Reference1",
    "reference": "Reference1",
    "delivery": "Reference1",
    "shipment_ref": "Reference1",
    # ── Reference2 ───────────────────────────────────────────────────
    "reference2": "Reference2",
    "ref2": "Reference2",
    "referentie 2": "Reference2",
    "customer reference number": "Reference2",
    # ── Reference3 ───────────────────────────────────────────────────
    "reference3": "Reference3",
    "ref3": "Reference3",
    "item barcode": "Reference3",
    "customer item id": "Reference3",
    # ── Container ────────────────────────────────────────────────────
    "container id": "Container ID",
    "container_id": "Container ID",
    "container label": "Container ID",
    "container_label": "Container ID",
    "container type": "Container Type",
    "container_type": "Container Type",
    # ── Pallet ───────────────────────────────────────────────────────
    "pallet id": "Pallet ID",
    "pallet_id": "Pallet ID",
    "pallet type": "Pallet Type",
    "pallet_type": "Pallet Type",
    # ── Collection ───────────────────────────────────────────────────
    "collection id": "Collection ID",
    "collection_id": "Collection ID",
    "collection type": "Collection Type",
    "collection_type": "Collection Type",
    # ── Internal Account ─────────────────────────────────────────────
    "internal account number/subclient": "Internal Account Number/Subclient",
    "internal account number": "Internal Account Number/Subclient",
    "internal_account_number": "Internal Account Number/Subclient",
    "subclient": "Internal Account Number/Subclient",
    # ── Shipper ──────────────────────────────────────────────────────
    "shipper name": "Shipper Name",
    "shipper_name": "Shipper Name",
    "shippers name": "Shipper Name",
    "seller": "Shipper Name",
    "sender company": "Shipper Name",
    "sender name": "Shipper Name",
    "afzender": "Shipper Name",
    "expéditeur": "Shipper Name",
    "versender": "Shipper Name",
    "shipper address 1": "Shipper Address 1",
    "ship add 1": "Shipper Address 1",
    "ship_add_1": "Shipper Address 1",
    "ship addr1": "Shipper Address 1",
    "sender address": "Shipper Address 1",
    "shipper address 2": "Shipper Address 2",
    "ship add 2": "Shipper Address 2",
    "ship_addr2": "Shipper Address 2",
    "shipper address 3": "Shipper Address 3",
    "ship add 3": "Shipper Address 3",
    "ship_addr3": "Shipper Address 3",
    "shipper city": "Shipper City",
    "ship city": "Shipper City",
    "ship_city": "Shipper City",
    "sender city": "Shipper City",
    "shipper state": "Shipper State",
    "ship state": "Shipper State",
    "ship_state": "Shipper State",
    "sender state": "Shipper State",
    "shipper zip/postcode": "Shipper Zip/Postcode",
    "ship zip": "Shipper Zip/Postcode",
    "ship_zip": "Shipper Zip/Postcode",
    "shipper zip": "Shipper Zip/Postcode",
    "sender postal code": "Shipper Zip/Postcode",
    "shipper country code": "Shipper Country Code",
    "ship country": "Shipper Country Code",
    "ship_country_code": "Shipper Country Code",
    "sender country code": "Shipper Country Code",
    "sender country": "Shipper Country Code",
    "shipper ioss": "Shipper IOSS",
    "shippers ioss": "Shipper IOSS",
    "ship ioss": "Shipper IOSS",
    "shippers_vat": "Shipper IOSS",
    "shippers vat": "Shipper IOSS",
    "sender id ref": "Shipper IOSS",
    "sender email": "Notes",
    "sender phone": "Notes",
    # ── Consignee ────────────────────────────────────────────────────
    "consignee": "Consignee",
    "consignee name": "Consignee",
    "receiver": "Consignee",
    "buyer": "Consignee",
    "addressee name": "Consignee",
    "addressee company": "Consignee",
    "ontvanger": "Consignee",
    "destinataire": "Consignee",
    "empfänger": "Consignee",
    "consignee address1": "Consignee Address1",
    "consignee address 1": "Consignee Address1",
    "address1": "Consignee Address1",
    "addressee address": "Consignee Address1",
    "consignee address2": "Consignee Address2",
    "consignee address 2": "Consignee Address2",
    "address2": "Consignee Address2",
    "addressee street name": "Consignee Address2",
    "consignee address3": "Consignee Address3",
    "consignee address 3": "Consignee Address3",
    "address3": "Consignee Address3",
    "consignee city": "Consignee City",
    "city": "Consignee City",
    "addressee city": "Consignee City",
    "consignee state": "Consignee State",
    "state": "Consignee State",
    "addressee state": "Consignee State",
    "consignee zip/postcode": "Consignee Zip/Postcode",
    "consignee zip": "Consignee Zip/Postcode",
    "zip": "Consignee Zip/Postcode",
    "addressee postal code": "Consignee Zip/Postcode",
    "consignee country code": "Consignee Country Code",
    "country": "Consignee Country Code",
    "country_code": "Consignee Country Code",
    "addressee country code": "Consignee Country Code",
    "addressee country": "Consignee Country Code",
    "consignee email": "Consignee Email",
    "email": "Consignee Email",
    "addressee email": "Consignee Email",
    "consignee phone": "Consignee Phone",
    "phone": "Consignee Phone",
    "addressee phone": "Consignee Phone",
    "consignee eori": "Consignee EORI",
    "consigneeeori": "Consignee EORI",
    "eori": "Consignee EORI",
    "addressee id ref": "Consignee EORI",
    # ── Package ──────────────────────────────────────────────────────
    "package type": "Package type",
    "package_type": "Package type",
    "pkg type": "Package type",
    "product": "Package type",
    "pieces": "Pieces",
    "pcs": "Pieces",
    # ── Item details ─────────────────────────────────────────────────
    "item quantity": "Item Quantity",
    "item_quantity": "Item Quantity",
    "qty": "Item Quantity",
    "quantity": "Item Quantity",
    "aantal": "Item Quantity",
    "quantité": "Item Quantity",
    "menge": "Item Quantity",
    "item weight": "Item Weight",
    "item_weight": "Item Weight",
    "item weight 1": "Item Weight",
    "unit weight": "Item Weight",
    "net weight in grams": "Item Weight",
    "stukgewicht": "Item Weight",
    "poids unitaire": "Item Weight",
    "einzelgewicht": "Item Weight",
    "item value": "Item Value",
    "item_value": "Item Value",
    "itemvalue": "Item Value",
    "item value 1": "Item Value",
    "unit value": "Item Value",
    "line weight": "Line Weight",
    "line_weight": "Line Weight",
    "line weight 1": "Line Weight",
    "line value": "Line Value",
    "line_value": "Line Value",
    "line value 1": "Line Value",
    "total weight": "Total Weight",
    "total_weight": "Total Weight",
    "total weight 1": "Total Weight",
    "gross weight": "Total Weight",
    "total weight (g)": "Total Weight",
    "gross wght(g)": "Total Weight",
    "total value": "Total Value",
    "total_value": "Total Value",
    "total value 1": "Total Value",
    "customs value": "Total Value",
    "total goods value": "Total Value",
    "douanewaarde": "Total Value",
    "valeur en douane": "Total Value",
    "zollwert": "Total Value",
    # ── Units & trade terms ──────────────────────────────────────────
    "weight uom": "Weight UOM",
    "weight_uom": "Weight UOM",
    "wgt uom": "Weight UOM",
    "currency": "Currency",
    "currency_code": "Currency",
    "currencycode": "Currency",
    "invoice currency": "Currency",
    "incoterms": "Incoterms",
    "incoterm": "Incoterms",
    "declaration type": "Incoterms",
    "shipping rate": "Shipping rate",
    "shipping_rate": "Shipping rate",
    "transport value": "Shipping rate",
    # ── Description & classification ─────────────────────────────────
    "description": "Description",
    "item description": "Description",
    "item_description": "Description",
    "goods description": "Description",
    "description of goods": "Description",
    "commodity": "Description",
    "goederenomschrijving": "Description",
    "description marchandise": "Description",
    "warenbeschreibung": "Description",
    "taric code": "TARIC code",
    "taric_code": "TARIC code",
    "hs code": "TARIC code",
    "hs_code": "TARIC code",
    "item hs code": "TARIC code",
    "item_hs_code": "TARIC code",
    "itemhscode": "TARIC code",
    "hscode": "TARIC code",
    "tariff": "TARIC code",
    "hs tariff code": "TARIC code",
    "item sku": "Item SKU",
    "item_sku": "Item SKU",
    "sku": "Item SKU",
    "item country of origin": "Item Country of origin",
    "item_countryoforigin": "Item Country of origin",
    "item country origin": "Item Country of origin",
    "country of origin": "Item Country of origin",
    "country of manufacture": "Item Country of origin",
    "origin": "Item Country of origin",
    # ── Other ────────────────────────────────────────────────────────
    "weblink": "Weblink",
    "sales weblink": "Weblink",
    "salesweblink": "Weblink",
    "web link": "Weblink",
    "item url": "Weblink",
    "notes": "Notes",
    "item additional info": "Notes",
    "item_additionalinfo": "Notes",
    "additional info": "Notes",
    "shipment additional info": "Notes",
    "shipment_additional_info": "Notes",
    "reason": "Notes",
    # Extra fields from real files
    "vendor": "Notes",
    "service": "Notes",
    "route": "Notes",
}

# Validation rules from the training pack
VALIDATION_RULES = {
    "Shipper Country Code": {"type": "iso_country", "max_length": 2, "required": False},
    "Consignee Country Code": {"type": "iso_country", "max_length": 2, "required": False},
    "Currency": {"type": "iso_currency", "max_length": 3, "required": False},
    "Weight UOM": {"type": "weight_uom", "allowed": ["KG", "KGS", "LBS", "LB"], "normalize_to": {"KGS": "KG", "LB": "LBS"}},
    "TARIC code": {"type": "taric", "min_length": 8, "max_length": 10},
    "Consignee Email": {"type": "email"},
    "Incoterms": {"type": "incoterm", "allowed": ["DDP", "DAP", "EXW", "FCA", "FOB", "CIF", "CPT", "CIP", "DAT", "DPU"]},
    "Item Quantity": {"type": "numeric", "min": 0},
    "Item Weight": {"type": "numeric", "min": 0},
    "Item Value": {"type": "numeric", "min": 0},
    "Total Weight": {"type": "numeric", "min": 0},
    "Total Value": {"type": "numeric", "min": 0},
    "Line Weight": {"type": "numeric", "min": 0},
    "Line Value": {"type": "numeric", "min": 0},
    "Shipping rate": {"type": "numeric", "min": 0},
}

# Step definitions for the frontend
STEP_DEFINITIONS = {
    "P1": {"title": "Data Extraction & Harmonization", "description": "Show processing transparency and completeness"},
    "P2": {"title": "AI Enrichment", "description": "AI-powered data enrichment and enhancement"},
    "P3": {"title": "Tariff Classification", "description": "Show classification reliability"},
    "P4": {"title": "Customs Value Calculation", "description": "Show value certainty and FX exposure"},
    "P5": {"title": "Risk Analysis", "description": "Risk assessment and fraud detection"},
    "P6": {"title": "Hub Comparison", "description": "Show network positioning across hubs"},
    "P7": {"title": "Duties & Taxes Simulation", "description": "Show fiscal differences per hub"},
    "P8": {"title": "eCommerce Eligibility", "description": "Show automation readiness"},
    "P9": {"title": "Integrity & Recovery", "description": "Show optimization progress"},
}